FROM babu479/devops-test
COPY /home/sindhura/.jenkins/workspace/task1/Java-project/target/java-web-project.war /root/apache-tomcat-7.0.42-v2/webapps/
ENTRYPOINT["bash /root/apache-tomcat-7.0.42-v2/bin/startup.sh "]


