node(''){
stage('Initilize'){
 def mavenhome = tool 'maven'
 env.PATH = "${mavenhome}/bin:${env.PATH}"
}
stage('clone'){
git branch: 'master',
credentialsId: '7b25d3fe-425b-4b0b-bfb6-827587a7fcb8',
url: 'https://github.com/babu479/Sunday.git'
}
stage('Build'){
sh '''
cd Java-project
mvn clean install'''
}
stage('Deploy'){
build job: 'Deploy'
}
}
