node(''){
stage('Initilize'){
 def mavenhome = tool 'maven'
 env.PATH = "${mavenhome}/bin:${env.PATH}"
}
stage('clone'){
git branch: 'master',
credentialsId: 'edb1f7cf-30e1-40cb-8591-5044e6b23e28',
url: 'https://github.com/babu479/Sunday.git'
}
stage('Build'){
sh '''
cd Java-project
mvn clean install'''
}

}
